package com.lottery.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDcDxp<M extends BaseDcDxp<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMatchId(java.lang.Integer matchId) {
		set("matchId", matchId);
		return (M)this;
	}

	public java.lang.Integer getMatchId() {
		return getInt("matchId");
	}

	public M setBig(java.lang.Double big) {
		set("big", big);
		return (M)this;
	}

	public java.lang.Double getBig() {
		return getDouble("big");
	}

	public M setBigChange(java.lang.Integer bigChange) {
		set("bigChange", bigChange);
		return (M)this;
	}

	public java.lang.Integer getBigChange() {
		return getInt("bigChange");
	}

	public M setPankou(java.lang.String pankou) {
		set("pankou", pankou);
		return (M)this;
	}

	public java.lang.String getPankou() {
		return getStr("pankou");
	}

	public M setPankouChange(java.lang.Integer pankouChange) {
		set("pankouChange", pankouChange);
		return (M)this;
	}

	public java.lang.Integer getPankouChange() {
		return getInt("pankouChange");
	}

	public M setSmall(java.lang.Double small) {
		set("small", small);
		return (M)this;
	}

	public java.lang.Double getSmall() {
		return getDouble("small");
	}

	public M setSmallChange(java.lang.Integer smallChange) {
		set("smallChange", smallChange);
		return (M)this;
	}

	public java.lang.Integer getSmallChange() {
		return getInt("smallChange");
	}

	public M setIsFirst(java.lang.Boolean isFirst) {
		set("isFirst", isFirst);
		return (M)this;
	}

	public java.lang.Boolean getIsFirst() {
		return get("isFirst");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setTerm(java.lang.String term) {
		set("term", term);
		return (M)this;
	}

	public java.lang.String getTerm() {
		return getStr("term");
	}

	public M setLineId(java.lang.String lineId) {
		set("lineId", lineId);
		return (M)this;
	}

	public java.lang.String getLineId() {
		return getStr("lineId");
	}

	public M setCompany(java.lang.String company) {
		set("company", company);
		return (M)this;
	}

	public java.lang.String getCompany() {
		return getStr("company");
	}

}
