package com.lottery.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserWalletlog<M extends BaseUserWalletlog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}

	public java.lang.String getAccount() {
		return getStr("account");
	}

	public M setTransType(java.lang.Integer transType) {
		set("transType", transType);
		return (M)this;
	}

	public java.lang.Integer getTransType() {
		return getInt("transType");
	}

	public M setTransMoney(java.math.BigDecimal transMoney) {
		set("transMoney", transMoney);
		return (M)this;
	}

	public java.math.BigDecimal getTransMoney() {
		return get("transMoney");
	}

	public M setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
		return (M)this;
	}

	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setOutId(java.lang.String outId) {
		set("outId", outId);
		return (M)this;
	}

	public java.lang.String getOutId() {
		return getStr("outId");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
