package com.lottery.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNewsContext<M extends BaseNewsContext<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContext(java.lang.String context) {
		set("context", context);
		return (M)this;
	}

	public java.lang.String getContext() {
		return getStr("context");
	}

	public M setSectionId(java.lang.Integer sectionId) {
		set("sectionId", sectionId);
		return (M)this;
	}

	public java.lang.Integer getSectionId() {
		return getInt("sectionId");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}

	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setIsDel(java.lang.Boolean isDel) {
		set("isDel", isDel);
		return (M)this;
	}

	public java.lang.Boolean getIsDel() {
		return get("isDel");
	}

	public M setViewCount(java.lang.Integer viewCount) {
		set("viewCount", viewCount);
		return (M)this;
	}

	public java.lang.Integer getViewCount() {
		return getInt("viewCount");
	}

	public M setLink(java.lang.String link) {
		set("link", link);
		return (M)this;
	}

	public java.lang.String getLink() {
		return getStr("link");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setTags(java.lang.String tags) {
		set("tags", tags);
		return (M)this;
	}

	public java.lang.String getTags() {
		return getStr("tags");
	}

	public M setIsTop(java.lang.Boolean isTop) {
		set("isTop", isTop);
		return (M)this;
	}

	public java.lang.Boolean getIsTop() {
		return get("isTop");
	}

	public M setDesc(java.lang.String desc) {
		set("desc", desc);
		return (M)this;
	}

	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public M setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
		return (M)this;
	}

	public java.lang.String getKeywords() {
		return getStr("keywords");
	}

	public M setPushTime(java.util.Date pushTime) {
		set("pushTime", pushTime);
		return (M)this;
	}

	public java.util.Date getPushTime() {
		return get("pushTime");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setIsShow(java.lang.Boolean isShow) {
		set("isShow", isShow);
		return (M)this;
	}

	public java.lang.Boolean getIsShow() {
		return get("isShow");
	}

	public M setSource(java.lang.String source) {
		set("source", source);
		return (M)this;
	}

	public java.lang.String getSource() {
		return getStr("source");
	}

}
