package com.lottery.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDcArrange<M extends BaseDcArrange<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setHome(java.lang.String home) {
		set("home", home);
		return (M)this;
	}

	public java.lang.String getHome() {
		return getStr("home");
	}

	public M setGuest(java.lang.String guest) {
		set("guest", guest);
		return (M)this;
	}

	public java.lang.String getGuest() {
		return getStr("guest");
	}

	public M setShortHome(java.lang.String shortHome) {
		set("shortHome", shortHome);
		return (M)this;
	}

	public java.lang.String getShortHome() {
		return getStr("shortHome");
	}

	public M setShortGuest(java.lang.String shortGuest) {
		set("shortGuest", shortGuest);
		return (M)this;
	}

	public java.lang.String getShortGuest() {
		return getStr("shortGuest");
	}

	public M setMatchTime(java.util.Date matchTime) {
		set("matchTime", matchTime);
		return (M)this;
	}

	public java.util.Date getMatchTime() {
		return get("matchTime");
	}

	public M setRqs(java.lang.Integer rqs) {
		set("rqs", rqs);
		return (M)this;
	}

	public java.lang.Integer getRqs() {
		return getInt("rqs");
	}

	public M setTerm(java.lang.String term) {
		set("term", term);
		return (M)this;
	}

	public java.lang.String getTerm() {
		return getStr("term");
	}

	public M setLineId(java.lang.String lineId) {
		set("lineId", lineId);
		return (M)this;
	}

	public java.lang.String getLineId() {
		return getStr("lineId");
	}

	public M setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
		return (M)this;
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public M setMatchName(java.lang.String matchName) {
		set("matchName", matchName);
		return (M)this;
	}

	public java.lang.String getMatchName() {
		return getStr("matchName");
	}

	public M setMatchDate(java.lang.String matchDate) {
		set("matchDate", matchDate);
		return (M)this;
	}

	public java.lang.String getMatchDate() {
		return getStr("matchDate");
	}

	public M setHalfScore(java.lang.String halfScore) {
		set("halfScore", halfScore);
		return (M)this;
	}

	public java.lang.String getHalfScore() {
		return getStr("halfScore");
	}

	public M setWholeScore(java.lang.String wholeScore) {
		set("wholeScore", wholeScore);
		return (M)this;
	}

	public java.lang.String getWholeScore() {
		return getStr("wholeScore");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setMatchColor(java.lang.String matchColor) {
		set("matchColor", matchColor);
		return (M)this;
	}

	public java.lang.String getMatchColor() {
		return getStr("matchColor");
	}

	public M setOddId(java.lang.String oddId) {
		set("oddId", oddId);
		return (M)this;
	}

	public java.lang.String getOddId() {
		return getStr("oddId");
	}

	public M setHomeId(java.lang.Integer homeId) {
		set("homeId", homeId);
		return (M)this;
	}

	public java.lang.Integer getHomeId() {
		return getInt("homeId");
	}

	public M setGuestId(java.lang.Integer guestId) {
		set("guestId", guestId);
		return (M)this;
	}

	public java.lang.Integer getGuestId() {
		return getInt("guestId");
	}

}
