package com.lottery.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("dc_arrange", "id", DcArrange.class);
		arp.addMapping("dc_dxp", "id", DcDxp.class);
		arp.addMapping("dc_op", "id", DcOp.class);
		arp.addMapping("dc_spf_sp", "id", DcSpfSp.class);
		arp.addMapping("dc_yp", "id", DcYp.class);
		arp.addMapping("lot_admin", "Id", LotAdmin.class);
		arp.addMapping("lot_user", "Id", LotUser.class);
		arp.addMapping("lot_user_buylog", "Id", LotUserBuylog.class);
		arp.addMapping("lottery_term", "id", LotteryTerm.class);
		arp.addMapping("news_context", "id", NewsContext.class);
		arp.addMapping("news_section", "id", NewsSection.class);
		arp.addMapping("news_template", "id", NewsTemplate.class);
	}
}

