package com.lottery.common.model;

import com.lottery.common.model.base.BaseDcDxp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DcDxp extends BaseDcDxp<DcDxp> {
	public static final DcDxp dao = new DcDxp().dao();
	
	
}
