package com.lottery.common.model;

import com.lottery.common.model.base.BaseDcOp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DcOp extends BaseDcOp<DcOp> {
	public static final DcOp dao = new DcOp().dao();
}
