package com.lottery.common.model;

import java.text.DecimalFormat;

import com.lottery.common.model.base.BaseDcSpfSp;
import com.lottery.common.utils.ArithUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DcSpfSp extends BaseDcSpfSp<DcSpfSp> {
	private String spStr;
	private DecimalFormat df = new DecimalFormat("0%");

	public String getSpStr() {
		return getHomeSp() + "_" + getDrawSp() + "_" + getGuestSp();
	}

	private Double homeBet;
	private Double guestBet;
	private Double drawBet;
	private String homeBetStr;

	private String guestBetStr;
	private String drawBetStr;

	public Double getHomeBet() {
		if (getHomeSp() == null || getHomeSp() == 0d) {
			homeBet = 0d;
		} else {
			homeBet = ArithUtil.div(1d, getHomeSp());
		}
		return homeBet;
	}

	public Double getGuestBet() {
		if (getGuestSp() == null || getGuestSp() == 0d) {
			guestBet = 0d;
		} else {
			guestBet = ArithUtil.div(1d, getGuestSp());
		}
		return guestBet;
	}

	public Double getDrawBet() {

		if (getDrawSp() == null || getDrawSp() == 0d) {
			drawBet = 0d;
		} else {
			drawBet = ArithUtil.div(1d, getDrawSp());
		}
		return drawBet;
	}

	public String getHomeBetStr() {
		homeBetStr = df.format(getHomeBet());
		return homeBetStr;
	}

	public String getGuestBetStr() {
		guestBetStr = df.format(getGuestBet());
		return guestBetStr;
	}

	public String getDrawBetStr() {
		drawBetStr = df.format(getDrawBet());
		return drawBetStr;
	}

}
