package com.lottery.common.model;

import java.math.BigDecimal;
import java.text.DecimalFormat;

import com.lottery.common.model.base.BaseDcSpfSp;
import com.lottery.common.utils.ArithUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DcSpfSp extends BaseDcSpfSp<DcSpfSp> {
	private String spStr;
	private DecimalFormat df = new DecimalFormat("0.0%");

	public String getSpStr() {
		return getHomeSp() + "_" + getDrawSp() + "_" + getGuestSp();
	}

	private Double homeBet;
	private Double guestBet;
	private Double drawBet;
	private String homeBetStr;

	private String guestBetStr;
	private String drawBetStr;

	public Double getHomeBet() {
		homeBet = ArithUtil.div(1d, getHomeSp());
		return homeBet;
	}

	public Double getGuestBet() {
		guestBet = ArithUtil.div(1d, getGuestSp());
		return guestBet;
	}

	public Double getDrawBet() {
		drawBet = ArithUtil.div(1d, getDrawSp());
		return drawBet;
	}

	public String getHomeBetStr() {
		homeBetStr = df.format(homeBet);
		return homeBetStr;
	}

	public String getGuestBetStr() {
		guestBetStr =df.format(guestBet);
		return guestBetStr;
	}

	public String getDrawBetStr() {
		drawBetStr =df.format(drawBet);
		return drawBetStr;
	}

}
