package com.lottery.common.model;

import com.lottery.common.model.base.BaseDcSpfSp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DcSpfSp extends BaseDcSpfSp<DcSpfSp> {
	private String spStr;

	public String getSpStr() {
		return getHomeSp()+"_"+getDrawSp()+"_"+getGuestSp();
	}
}
