package com.lottery.common.model;

import java.text.DecimalFormat;

import com.alibaba.fastjson.annotation.JSONField;
import com.lottery.common.model.base.BaseDcYp;
import com.lottery.common.utils.YpPKGainScale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DcYp extends BaseDcYp<DcYp> {

	 @JSONField(serialize=false)  
	/**
	 * 获取新版单场页面亚盘的盈利比数据
	 * 
	 * @param sp
	 * @param concede
	 * @return
	 */
	public void getNewylb(DcSpfSp dcSp, int concede) {
		if (dcSp != null ) {
			Double[] betScale = new Double[] { dcSp.getHomeBet() / 100, dcSp.getDrawBet() / 100,
					dcSp.getGuestBet() / 100 };
			Double[] waterLevel = new Double[] { getHome(), getGuest() };
			Double[] result = YpPKGainScale.getGainScale(betScale, waterLevel, concede, getNumPankou());
			if (result[0] != null) {
				DecimalFormat df = new DecimalFormat("0%");
				DecimalFormat df1 = new DecimalFormat("0.0");
				setHomeYlb(df.format(result[0]));
				setGuestYlb(df.format(result[1]));
				setHomeIsMinus(result[0]<0);
				setGuestIsMinus(result[1]<0);
				String pkylb = "(" + df1.format((Math.abs(result[0]) + Math.abs(result[1])) * 100) + ")";
				setPkYlb(pkylb);
			}
		}
	}

	// 盈利比
	private String homeYlb;
	private Boolean homeIsMinus;//是否负数

	private Boolean guestIsMinus;//是否负数
	private String guestYlb;
	private String pkYlb;

	public String getHomeYlb() {
		return homeYlb;
	}

	public void setHomeYlb(String homeYlb) {
		this.homeYlb = homeYlb;
	}

	public String getGuestYlb() {
		return guestYlb;
	}

	public void setGuestYlb(String guestYlb) {
		this.guestYlb = guestYlb;
	}

	public String getPkYlb() {
		return pkYlb;
	}

	public void setPkYlb(String pkYlb) {
		this.pkYlb = pkYlb;
	}

	public Boolean getHomeIsMinus() {
		return homeIsMinus;
	}

	public void setHomeIsMinus(Boolean homeIsMinus) {
		this.homeIsMinus = homeIsMinus;
	}

	public Boolean getGuestIsMinus() {
		return guestIsMinus;
	}

	public void setGuestIsMinus(Boolean guestIsMinus) {
		this.guestIsMinus = guestIsMinus;
	}

}
