package com.lottery.common.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.lottery.common.model.base.BaseDcYp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DcYp extends BaseDcYp<DcYp> {
	
	
	public static final Map<String, String> COMAPNY=new HashMap<String, String>();
	public static final List<String> COMAPNYLIST=new ArrayList<String>();
	public static final Map<String,String> WBW2CLLCOMPANY=new HashMap<String, String>();
	static{
		COMAPNY.put("永利高","yongligao");
		COMAPNY.put("皇冠","huangguan");
		COMAPNY.put( "伟德","weide");
		COMAPNY.put( "立博","libo");
		COMAPNY.put("澳门", "aomen");
		COMAPNY.put("bet365","ribo");
		COMAPNY.put("易胜博","yisheng");
		COMAPNY.put("明陞","mingsheng");
		COMAPNY.put("利记","liji");
		COMAPNY.put("nikebet","nikebet");
		COMAPNY.put("沙巴","shaba");
		
		WBW2CLLCOMPANY.put("永利高", "永利高");
		WBW2CLLCOMPANY.put("Singbet(皇冠)", "皇冠");
		WBW2CLLCOMPANY.put("伟德", "伟德");
		WBW2CLLCOMPANY.put("立博", "立博");
		WBW2CLLCOMPANY.put("澳门", "澳门");
		WBW2CLLCOMPANY.put("Bet365", "bet365");
		WBW2CLLCOMPANY.put("Easybets(易胜博)", "易胜博");
		WBW2CLLCOMPANY.put("明陞", "明陞");
		WBW2CLLCOMPANY.put("Sbobet(利记)", "利记");
		WBW2CLLCOMPANY.put("Nikebet", "nikebet");
		WBW2CLLCOMPANY.put("沙巴(IBCBET)", "沙巴");
		
		COMAPNYLIST.add("yongligao");
		COMAPNYLIST.add("huangguan");
		COMAPNYLIST.add("weide");
		COMAPNYLIST.add("libo");
		COMAPNYLIST.add("aomen");
		COMAPNYLIST.add("ribo");
		COMAPNYLIST.add("yisheng");
		COMAPNYLIST.add("mingsheng");
		COMAPNYLIST.add("liji");
		COMAPNYLIST.add("nikebet");
		COMAPNYLIST.add("shaba");
	}
	//盈利比
	private String homeBet;
	public String getHomeBet() {
		return homeBet;
	}
	public void setHomeBet(String homeBet) {
		this.homeBet = homeBet;
	}
	public String getGuestBet() {
		return guestBet;
	}
	public void setGuestBet(String guestBet) {
		this.guestBet = guestBet;
	}
	private String guestBet;
	

}
