package com.lottery.common.model;

import com.lottery.common.model.base.BaseLotAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotAdmin extends BaseLotAdmin<LotAdmin> {
}
