package com.lottery.common.model;

import com.lottery.common.model.base.BaseLotteryTerm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotteryTerm extends BaseLotteryTerm<LotteryTerm> {
}
