package com.lottery.common.model;

import com.lottery.common.model.base.BaseLotUserBuylog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotUserBuylog extends BaseLotUserBuylog<LotUserBuylog> {
	public static final LotUserBuylog dao = new LotUserBuylog().dao();
}
