package com.lottery.common.model;

import com.lottery.common.model.base.BaseLotUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotUser extends BaseLotUser<LotUser> {
}
