package com.lottery.common.model;

import com.lottery.common.model.base.BaseLotUserBuylog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotUserBuylog extends BaseLotUserBuylog<LotUserBuylog> {
	
	private String name;
	private String account;
	private String tel;
	public String getName() {
		return getStr("name");
	}
	public String getAccount() {
		return getStr("account");
	}
	public String getTel() {
		return getStr("tel");
	}


}
