package com.lottery.common.model;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.kit.Base64Kit;
import com.jfinal.kit.StrKit;
import com.lottery.common.model.base.BaseNewsTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsTemplate extends BaseNewsTemplate<NewsTemplate> {

	@JSONField(serialize=false)
	private String decodeContext;

	public String getDecodeContext() {
		return StrKit.isBlank(getContext()) ? "" : Base64Kit.decodeToStr(getContext());
	}

	public void setDecodeContext(String decodeContext) {
		this.decodeContext = decodeContext;
		setContext(this.decodeContext);
	}
}
