package com.lottery.common.model;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.kit.Base64Kit;
import com.jfinal.kit.StrKit;
import com.lottery.common.model.base.BaseNewsContext;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsContext extends BaseNewsContext<NewsContext> {
	
	@JSONField(serialize=false)
	private String decodeContext;

	public String getDecodeContext() {
		return StrKit.isBlank(getContext()) ? "" : Base64Kit.decodeToStr(getContext());
	}

	public void setDecodeContext(String decodeContext) {
		this.decodeContext = decodeContext;
		setContext(this.decodeContext);
	}
	
	
	@JSONField(serialize=false)
	private String decodeFreeContext;

	public String getDecodeFreeContext() {
		return StrKit.isBlank(getFreeContext()) ? "" : Base64Kit.decodeToStr(getFreeContext());
	}

	public void setDecodeFreeContext(String decodeFreeContext) {
		this.decodeFreeContext = decodeFreeContext;
		setFreeContext(this.decodeFreeContext);
	}
	
	private String sectionName;


	public String getSectionName() {
		return getStr("name");
	}
}
