package com.lottery.common.model;

import com.lottery.common.model.base.BaseNewsSection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsSection extends BaseNewsSection<NewsSection> {
}
