package com.lottery.common.model;

import com.lottery.common.model.base.BaseSysError;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysError extends BaseSysError<SysError> {
}
