package com.lottery.common.model;

import com.lottery.common.model.base.BaseUserWallet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserWallet extends BaseUserWallet<UserWallet> {
}
