package com.lottery.common.model;

import com.lottery.common.model.base.BaseUserWalletlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserWalletlog extends BaseUserWalletlog<UserWalletlog> {
	
	
	public enum TransTypeEnum{
		Out,In
	}
}
