package com.lottery.common.model;

import com.lottery.common.model.base.BaseUserBuy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserBuy extends BaseUserBuy<UserBuy> {
	
	
	public enum TypeEnum{
		News
	}
}
