package com.lottery.common.model;

import com.lottery.common.model.base.BaseUserRecharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRecharge extends BaseUserRecharge<UserRecharge> {
}
